language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev --three
  - pipenv shell -c
# command to run tests
script:
  - pipenv run cookiecutter . --output-dir /tmp --no-input && \
	cd /tmp/yourapplication && \
	make test
